dist: focal
arch:
  - ppc64le
language: python
install:
  - sudo apt-get update -y
  - sudo apt-get install -y build-essential g++ flex bison ruby perl libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev libpng-dev libjpeg-dev python libx11-dev libxext-dev 
  - sudo apt-get install -y "^libxcb.*" libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev

script:
  - export QT_QPA_PLATFORM=offscreen
  - cd phantomjs && git checkout 2.1.1 && git submodule init && git submodule update && ./build.py -c
