dist: bionic
arch:
  - ppc64le
language: python
before-install:
 - sudo apt-get update -y
 - sudo apt-get install -y build-essential g++ flex bison gperf 
 - sudo apt-get install -y "^libxcb.*" libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev


 script:
  - python build.py --confirm --release --qt-config="-no-pkg-config" --git-clean-qtbase --git-clean-qtwebkit
